#!/usr/bin/env node
/**
 * Generate `docs/graph/generated.md` from the Graph IR, and fail fast if the
 * graph is structurally invalid. The generated doc is committed; the release
 * gate regenerates it and asserts no drift (so a graph change without a doc
 * regeneration fails CI).
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { FDE_GRAPH, GRAPH_VERSION } from "../dist/graph/fde-graph.js";
import { toMermaid, toEdgeCatalog } from "../dist/graph/generators.js";
import { validateGraph } from "../dist/graph/validator.js";
import { PHASE_TRANSITIONS } from "../dist/graph/phase-spec.js";

const issues = validateGraph(FDE_GRAPH);
if (issues.length > 0) {
  for (const issue of issues) {
    process.stderr.write(`[${issue.severity}] ${issue.message}\n`);
  }
  process.stderr.write("release gate: graph validation FAILED\n");
  process.exit(1);
}

const mermaid = toMermaid(FDE_GRAPH);
const catalog = toEdgeCatalog(FDE_GRAPH);
const transitions = PHASE_TRANSITIONS.map((t) => `- ${t.from} → ${t.to}`).join("\n");

const doc = [
  `# Generated Graph Docs`,
  ``,
  `> graphVersion: ${GRAPH_VERSION} — regenerated by \`scripts/generate-docs.mjs\`. Do not edit by hand.`,
  ``,
  `## Mermaid`,
  ``,
  `\`\`\`mermaid`,
  mermaid,
  `\`\`\``,
  ``,
  `## Edge Catalog`,
  ``,
  catalog,
  ``,
  `## Phase Transitions`,
  ``,
  transitions,
  ``,
].join("\n") + "\n";

const out = fileURLToPath(new URL("../docs/graph/generated.md", import.meta.url));
writeFileSync(out, doc);
process.stdout.write("generated docs/graph/generated.md\n");
